module.exports = {
  "plugins": [
    '@typescript-eslint'
  ],
  "parser": '@typescript-eslint/parser',
  "rules": {
    'prefer-spread': 'error',
    'prefer-rest-params': 'error',
    'prefer-promise-reject-errors': 'error',
    'prefer-const': 'error',
    'no-with': 'error',
    'no-var': 'error',
    'no-unsafe-negation': 'error',
    'no-unreachable': 'error',
    'no-undef': 'error',
    'no-this-before-super': 'error',
    'no-setter-return': 'error',
    'no-obj-calls': 'error',
    'no-new-symbol': 'error',
    'no-new-object': 'error',
    'no-multi-str': 'error',
    'no-import-assign': 'error',
    'no-func-assign': 'error',
    'no-extra-bind': 'error',
    'no-extend-native': 'error',
    'no-dupe-keys': 'error',
    'no-dupe-args': 'error',
    'no-const-assign': 'error',
    'no-caller': 'error',
    'new-cap': 'error',
    'guard-for-in': 'error',
    'getter-return': 'error',
    'constructor-super': 'error',
    'no-throw-literal': 'error',
    '@typescript-eslint/no-unused-vars': 'warn',
    '@typescript-eslint/no-unnecessary-type-constraint': 'error',
    '@typescript-eslint/no-loss-of-precision': 'error',
    '@typescript-eslint/no-invalid-this': 'error',
    '@typescript-eslint/no-explicit-any': 'error',
    '@typescript-eslint/no-empty-interface': 'error',
    '@typescript-eslint/no-dupe-class-members': 'error',
    '@typescript-eslint/no-array-constructor': 'error',
    '@typescript-eslint/ban-types': 'error',
    '@typescript-eslint/ban-ts-comment': 'error',
    '@typescript-eslint/adjacent-overload-signatures': 'error',
  },
};
